import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Ubuntu } from "next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const ubuntu = Ubuntu({
  subsets: ["latin"],
  display: "swap",
  style: ["normal"],
  weight: ["400", "500", "700"],
});
export const metadata: Metadata = {
  title: "Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
